# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 279baaaa2d4b0a18b05eb37f1250500330e3e2dac528ddd3a4dd4cdab53fe4b8164600f815a010a2872a5c2d70c95a5f6134956d9a7c8361efd92f2492bcb079

test:
  secret_key_base: c689397492163019eb3d20f521a72848b86fe9e9708a55e9056c69a178bb41b57bd06ff04e3db2de762aadee1d0640de29bea365097856267d296c8bc6fe4e1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
